import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/header/nav/nav";
import { GlobalContextProvider } from "./components/context";
import Footer from "./components/footer/footer";
import ScrolledNav from "./components/header/scrolled Nav/scrolledNav";
import Login from "./components/header/nav/links-with-login/loginCartSearch/login";
import SignUp from "./components/header/nav/links-with-login/loginCartSearch/signUp";
import CartItems from "./components/header/nav/links-with-login/loginCartSearch/cartItems";
import { Suspense } from "react";
import Loading from "./loading";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <GlobalContextProvider>
              <CartItems />
              <Login />
              <SignUp />
              <Nav />
              <Suspense fallback={<Loading />}>
                {children}
              </Suspense>
              {/* <ScrolledNav /> */}
              <Footer />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
